name: Universal Flipper Binary

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Generates a universal Flipper Binary.
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        run: |
          chmod +x generate.sh && ./generate.sh
      - name: Archive generated universal Flipper binary
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            flipper/dist
            !flipper/dist/mac-universal/**/*
